"""core records

The five core records plus CaptureRecipe, LabeledExample and Ruling, with the
supporting Project, AppUser and SourceDocument tables the foreign keys need.

Everything after the autogenerated block is hand-written: the safety invariants
belong in the database, not in a comment or a service-layer check that a future
caller can forget to go through.

Revision ID: 902b548f4abd
Revises:
Create Date: 2026-09-17 17:54:34.407897
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "902b548f4abd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Nothing uses vectors in Phase 1. The extension is created here so the
    # database matches what infra/docker-compose.yml provisions, rather than
    # appearing later in a migration that also needs it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("oidc_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "roles",
            postgresql.ARRAY(sa.Enum("tech", "reviewer", "curator", "admin", name="user_role")),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oidc_subject", name="uq_app_user_oidc_subject"),
    )
    op.create_table(
        "capture_recipe",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column(
            "verification_method",
            sa.Enum("visual", "measured", "tested", "documentary", name="verification_method"),
            nullable=False,
        ),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("disqualifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reference_media_slot", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", "version", name="uq_capture_recipe_slug_version"),
    )
    op.create_table(
        "project",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cxalloy_project_id", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=200), nullable=False),
        sa.Column("equipment_class", sa.String(length=64), nullable=False),
        sa.Column("system", sa.String(length=200), nullable=False),
        sa.Column("location_room", sa.String(length=200), nullable=True),
        sa.Column("location_grid_ref", sa.String(length=50), nullable=True),
        sa.Column("location_type", sa.String(length=100), nullable=True),
        sa.Column("location_model_x", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("location_model_y", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("location_model_z", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("parent_asset", sa.UUID(), nullable=True),
        sa.Column("cxalloy_id", sa.String(length=100), nullable=True),
        sa.Column(
            "reconciliation_status",
            sa.Enum("auto_matched", "human_confirmed", "unresolved", name="reconciliation_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_asset"], ["asset.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "tag", name="uq_asset_project_tag"),
    )
    op.create_index(
        "ix_asset_project_equipment_class", "asset", ["project_id", "equipment_class"], unique=False
    )
    op.create_table(
        "source_document",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "spec_section",
                "approved_submittal",
                "manufacturer_iom",
                "standard",
                "rfi_response",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_alias",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("normalized_value", sa.String(length=200), nullable=False),
        sa.Column(
            "source",
            sa.Enum("cxalloy", "drawing_schedule", "submittal", "nameplate", name="alias_source"),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "value", "source", name="uq_asset_alias_value_source"),
    )
    op.create_index(
        "ix_asset_alias_normalized_value", "asset_alias", ["normalized_value"], unique=False
    )
    op.create_table(
        "asset_submittal",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("submittal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submittal_id"], ["source_document.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("asset_id", "submittal_id"),
    )
    op.create_table(
        "requirement",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "applies_to_equipment_class", postgresql.ARRAY(sa.String(length=64)), nullable=False
        ),
        sa.Column("applies_to_system", sa.String(length=200), nullable=True),
        sa.Column("applies_to_location_type", sa.String(length=100), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "verification_method",
            sa.Enum("visual", "measured", "tested", "documentary", name="verification_method"),
            nullable=False,
        ),
        sa.Column("evidence_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pass_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "criticality",
            sa.Enum("safety", "contractual", "quality", name="criticality"),
            nullable=False,
        ),
        sa.Column("source_doc_id", sa.UUID(), nullable=False),
        sa.Column("source_clause", sa.String(length=200), nullable=False),
        sa.Column("source_page", sa.Integer(), nullable=False),
        sa.Column("precedence_rank", sa.Integer(), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "needs_review", "approved", "retired", name="requirement_status"),
            nullable=False,
        ),
        sa.Column("ruleset_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "criticality <> 'safety' OR char_length(why_it_matters) >= 20",
            name="ck_requirement_safety_has_real_reason",
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR jsonb_array_length(evidence_spec) > 0",
            name="ck_requirement_approved_has_evidence_spec",
        ),
        sa.CheckConstraint(
            "precedence_rank >= 0", name="ck_requirement_precedence_rank_non_negative"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_doc_id"], ["source_document.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checklist_item",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("requirement_id", sa.UUID(), nullable=False),
        sa.Column("ruleset_version", sa.String(length=20), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "open",
                "evidence_captured",
                "auto_cleared",
                "routed",
                "reviewer_passed",
                "reviewer_failed",
                "blocked",
                name="checklist_item_state",
            ),
            nullable=False,
        ),
        sa.Column("assigned_tech", sa.UUID(), nullable=True),
        sa.Column("reviewer", sa.UUID(), nullable=True),
        sa.Column(
            "grader_result_id",
            sa.UUID(),
            nullable=True,
            comment="Always null in Phase 1; no grader exists.",
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column(
            "blocked_reason",
            sa.Enum(
                "no_access",
                "energized",
                "not_installed_yet",
                "equipment_missing",
                "tool_unavailable",
                "other",
                name="blocked_reason",
            ),
            nullable=True,
        ),
        sa.Column("blocked_note", sa.String(length=1000), nullable=True),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cxalloy_delivery_state",
            sa.Enum(
                "not_applicable",
                "pending_export",
                "exported",
                "delivery_confirmed",
                name="cxalloy_delivery_state",
            ),
            nullable=False,
        ),
        sa.Column("export_key", sa.String(length=200), nullable=True),
        sa.Column("cxalloy_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cxalloy_delivery_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cxalloy_delivery_confirmed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cxalloy_delivery_state <> 'delivery_confirmed' OR (cxalloy_delivery_confirmed_by IS NOT NULL AND cxalloy_delivery_confirmed_at IS NOT NULL)",
            name="ck_checklist_item_delivery_confirmed_by_a_person",
        ),
        sa.CheckConstraint(
            "state <> 'blocked' OR (blocked_reason IS NOT NULL AND blocked_at IS NOT NULL)",
            name="ck_checklist_item_blocked_has_reason",
        ),
        sa.CheckConstraint(
            "state NOT IN ('reviewer_passed', 'reviewer_failed') OR (resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND reviewer IS NOT NULL)",
            name="ck_checklist_item_ruling_names_a_person",
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["assigned_tech"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["cxalloy_delivery_confirmed_by"], ["app_user.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirement.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "asset_id",
            "requirement_id",
            "ruleset_version",
            name="uq_checklist_item_asset_requirement_ruleset",
        ),
    )
    op.create_index(
        "ix_checklist_item_reviewer_state", "checklist_item", ["reviewer", "state"], unique=False
    )
    op.create_index("ix_checklist_item_state", "checklist_item", ["state"], unique=False)
    op.create_index(
        "ix_checklist_item_undelivered",
        "checklist_item",
        ["cxalloy_delivery_state"],
        unique=False,
        postgresql_where="cxalloy_delivery_state IN ('pending_export', 'exported')",
    )
    op.create_table(
        "evidence",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("checklist_item_id", sa.UUID(), nullable=False),
        sa.Column("capture_recipe_id", sa.UUID(), nullable=False),
        sa.Column("capture_recipe_version", sa.String(length=20), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum("photo", "video", "document", "measurement", name="media_type"),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_by", sa.UUID(), nullable=False),
        sa.Column("device_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gate_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retake_of", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending_upload", "stored", "superseded", "rejected", name="evidence_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name="ck_evidence_content_hash_is_sha256"
        ),
        sa.CheckConstraint("byte_size > 0", name="ck_evidence_byte_size_positive"),
        sa.CheckConstraint("step_index >= 0", name="ck_evidence_step_index_non_negative"),
        sa.ForeignKeyConstraint(["capture_recipe_id"], ["capture_recipe.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["captured_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["checklist_item_id"], ["checklist_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["retake_of"], ["evidence.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", name="uq_evidence_client_id"),
    )
    op.create_index("ix_evidence_checklist_item", "evidence", ["checklist_item_id"], unique=False)
    op.create_table(
        "grader_result",
        sa.Column("checklist_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("pass", "fail", "insufficient_evidence", name="grader_verdict"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("grader_id", sa.String(length=100), nullable=False),
        sa.Column("grader_version", sa.String(length=20), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "verdict <> 'insufficient_evidence' OR confidence <= 0.5",
            name="ck_grader_result_insufficient_is_not_confident",
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_grader_result_confidence_range"
        ),
        sa.CheckConstraint(
            "jsonb_array_length(evidence_used) > 0", name="ck_grader_result_cites_evidence"
        ),
        sa.ForeignKeyConstraint(["checklist_item_id"], ["checklist_item.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ruling",
        sa.Column("checklist_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("pass", "fail", "recapture_requested", name="ruling_verdict"),
            nullable=False,
        ),
        sa.Column(
            "note",
            sa.Text(),
            nullable=True,
            comment="The reviewer's one-line note. Ruling and note are one action in the console; the flywheel starves if reviewers clear items silently.",
        ),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column(
            "supersedes",
            sa.UUID(),
            nullable=True,
            comment="A correction points at the ruling it replaces. Both stay readable.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["checklist_item_id"], ["checklist_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes"], ["ruling.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ruling_checklist_item_created",
        "ruling",
        ["checklist_item_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ruling_reviewer_created", "ruling", ["reviewer_id", "created_at"], unique=False
    )
    op.create_table(
        "labeled_example",
        sa.Column("ruling_id", sa.UUID(), nullable=False),
        sa.Column("checklist_item_id", sa.UUID(), nullable=False),
        sa.Column("requirement_id", sa.UUID(), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "item_type",
            sa.String(length=100),
            nullable=False,
            comment="The grouping calibration and golden sets are computed per.",
        ),
        sa.Column(
            "grader_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="The full grader record. Null throughout Phase 1.",
        ),
        sa.Column(
            "human_verdict",
            sa.Enum("pass", "fail", "recapture_requested", name="ruling_verdict"),
            nullable=False,
        ),
        sa.Column("human_note", sa.Text(), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("labeled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "weight",
            sa.Float(),
            nullable=False,
            comment="A reviewer label weighs 1.0. The tech's predict-then-reveal call is stored as a second label with lower weight in Phase 2.",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["checklist_item_id"], ["checklist_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirement.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["ruling_id"], ["ruling.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ruling_id", name="uq_labeled_example_ruling"),
    )
    op.create_index("ix_labeled_example_item_type", "labeled_example", ["item_type"], unique=False)
    op.create_index("ix_labeled_example_reviewer", "labeled_example", ["reviewer_id"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Invariants enforced by the database.
    #
    # CLAUDE.md requires these in code rather than in comments. Putting them
    # here means they hold for every writer: the API, a migration, a Celery
    # task, and a person with a psql prompt at 2am.
    # ------------------------------------------------------------------

    op.execute(
        """
        CREATE OR REPLACE FUNCTION fie_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                '% is append-only: rows cannot be % (attempted on id %)',
                TG_TABLE_NAME,
                lower(TG_OP) || 'd',
                COALESCE(OLD.id::text, '?')
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # A correction is a new ruling, never an edit to an old one. Same for the
    # labelled examples derived from them: training data that can be rewritten
    # after the fact is not evidence of anything.
    for table in ("ruling", "labeled_example"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION fie_forbid_mutation();
            """
        )

    # The non-negotiable rule. criticality lives on requirement, so this cannot
    # be a CHECK constraint; a trigger is the only way to enforce it in the
    # database. Phase 1 has no grader and so can never reach auto_cleared, but
    # the guard ships now so that Phase 2 cannot introduce the failure quietly.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fie_forbid_safety_auto_clear() RETURNS trigger AS $$
        DECLARE
            item_criticality criticality;
        BEGIN
            IF NEW.state <> 'auto_cleared' THEN
                RETURN NEW;
            END IF;

            SELECT r.criticality INTO item_criticality
            FROM requirement r
            WHERE r.id = NEW.requirement_id;

            IF item_criticality = 'safety' THEN
                RAISE EXCEPTION
                    'checklist_item % cannot be auto_cleared: its requirement is criticality safety and requires a named reviewer',
                    NEW.id
                    USING ERRCODE = 'restrict_violation';
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_checklist_item_no_safety_auto_clear
        BEFORE INSERT OR UPDATE ON checklist_item
        FOR EACH ROW EXECUTE FUNCTION fie_forbid_safety_auto_clear();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_checklist_item_no_safety_auto_clear ON checklist_item")
    op.execute("DROP FUNCTION IF EXISTS fie_forbid_safety_auto_clear()")
    for table in ("ruling", "labeled_example"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS fie_forbid_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_labeled_example_reviewer", table_name="labeled_example")
    op.drop_index("ix_labeled_example_item_type", table_name="labeled_example")
    op.drop_table("labeled_example")
    op.drop_index("ix_ruling_reviewer_created", table_name="ruling")
    op.drop_index("ix_ruling_checklist_item_created", table_name="ruling")
    op.drop_table("ruling")
    op.drop_table("grader_result")
    op.drop_index("ix_evidence_checklist_item", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(
        "ix_checklist_item_undelivered",
        table_name="checklist_item",
        postgresql_where="cxalloy_delivery_state IN ('pending_export', 'exported')",
    )
    op.drop_index("ix_checklist_item_state", table_name="checklist_item")
    op.drop_index("ix_checklist_item_reviewer_state", table_name="checklist_item")
    op.drop_table("checklist_item")
    op.drop_table("requirement")
    op.drop_table("asset_submittal")
    op.drop_index("ix_asset_alias_normalized_value", table_name="asset_alias")
    op.drop_table("asset_alias")
    op.drop_table("source_document")
    op.drop_index("ix_asset_project_equipment_class", table_name="asset")
    op.drop_table("asset")
    op.drop_table("project")
    op.drop_table("capture_recipe")
    op.drop_table("app_user")
    # ### end Alembic commands ###

    # Dropping the tables does not drop the enum types they used, so a
    # downgrade followed by an upgrade would fail on "type already exists".
    for enum_name in (
        "alias_source",
        "blocked_reason",
        "checklist_item_state",
        "criticality",
        "cxalloy_delivery_state",
        "document_type",
        "evidence_status",
        "grader_verdict",
        "media_type",
        "reconciliation_status",
        "requirement_status",
        "ruling_verdict",
        "user_role",
        "verification_method",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
