"""reconciliation queue

The queue the tag reconciler puts anything it will not decide into. Its size is
a tracked metric: the architecture doc calls a growing unresolved queue a
leading indicator that the field is walking to wrong assets.

Revision ID: 4c3e25ca5a2f
Revises: 902b548f4abd
Create Date: 2026-09-17 18:39:35.703131
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4c3e25ca5a2f"
down_revision: str | None = "902b548f4abd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_queue_item",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "raw_tag",
            sa.String(length=200),
            nullable=False,
            comment="Exactly what the source said.",
        ),
        sa.Column("normalized_tag", sa.String(length=200), nullable=False),
        # alias_source is created by 0001 and owned by it. Autogenerate emits a
        # fresh sa.Enum here, which would try to CREATE TYPE a second time; any
        # later migration reusing an existing enum needs create_type=False.
        sa.Column(
            "source", postgresql.ENUM(name="alias_source", create_type=False), nullable=False
        ),
        sa.Column("observed_equipment_class", sa.String(length=64), nullable=True),
        sa.Column("observed_location_room", sa.String(length=200), nullable=True),
        sa.Column(
            "reason",
            sa.Enum("no_match", "low_confidence", "ambiguous", name="reconciliation_queue_reason"),
            nullable=False,
        ),
        sa.Column(
            "explanation",
            sa.Text(),
            nullable=False,
            comment="Why the reconciler would not decide, in plain words.",
        ),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="What the reconciler considered and how it scored, so the person sees what it saw.",
        ),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", "dismissed", name="reconciliation_queue_status"),
            nullable=False,
        ),
        sa.Column("resolved_asset_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'resolved' OR (resolved_by IS NOT NULL AND resolved_at IS NOT NULL)",
            name="ck_reconciliation_queue_resolved_by_a_person",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_asset_id"], ["asset.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reconciliation_queue_status", "reconciliation_queue_item", ["status"], unique=False
    )
    op.create_index(
        "uq_reconciliation_queue_open_observation",
        "reconciliation_queue_item",
        ["project_id", "normalized_tag", "source"],
        unique=True,
        postgresql_where="status = 'open'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_reconciliation_queue_open_observation",
        table_name="reconciliation_queue_item",
        postgresql_where="status = 'open'",
    )
    op.drop_index("ix_reconciliation_queue_status", table_name="reconciliation_queue_item")
    op.drop_table("reconciliation_queue_item")
    # ### end Alembic commands ###

    # Same trap as 0001: dropping the table leaves its enum types behind.
    for enum_name in ("reconciliation_queue_reason", "reconciliation_queue_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
