"""document pages

Ingestion output: one row per page of text, with the rendered page image in
object storage, plus the document-level text-layer verdict that decides whether
extraction can run at all.

Revision ID: 6981fa1b6037
Revises: 4ed9943aba2a
Create Date: 2026-09-17 20:06:38.638459
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6981fa1b6037"
down_revision: str | None = "4ed9943aba2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # op.add_column does not create the enum type the column needs, unlike
    # op.create_table. See alembic/README.md.
    text_layer_status = postgresql.ENUM(
        "present", "partial", "missing", name="text_layer_status", create_type=False
    )
    text_layer_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_page",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "page_number",
            sa.Integer(),
            nullable=False,
            comment="1-indexed, as a person reading the document would say.",
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("image_storage_key", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["source_document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_number", name="uq_document_page_number"),
    )
    op.add_column(
        "source_document",
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
            comment="sha256 of the uploaded bytes. Re-uploading the same file is a no-op.",
        ),
    )
    op.add_column("source_document", sa.Column("page_count", sa.Integer(), nullable=True))
    op.add_column(
        "source_document",
        sa.Column(
            "text_layer_status",
            sa.Enum("present", "partial", "missing", name="text_layer_status"),
            nullable=True,
            comment="A document without a text layer is flagged for a person, never silently OCR'd and never silently dropped. See docs/OPEN_QUESTIONS.md Q2.",
        ),
    )
    op.add_column(
        "source_document", sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_document", "ingested_at")
    op.drop_column("source_document", "text_layer_status")
    op.drop_column("source_document", "page_count")
    op.drop_column("source_document", "content_hash")
    op.drop_table("document_page")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS text_layer_status")
