"""precedence conflicts

Grouping requirements that govern the same check, and somewhere to put the ones
the precedence rules will not settle.

requirement.check_key is added with add_column, which does not need a new enum;
requirement_conflict.status does, and create_table handles it. See
alembic/README.md for why those two behave differently.

Revision ID: 48f61c45ef60
Revises: 6981fa1b6037
Create Date: 2026-09-17 20:23:45.228788
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "48f61c45ef60"
down_revision: str | None = "6981fa1b6037"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_conflict",
        sa.Column("rule_set_id", sa.UUID(), nullable=False),
        sa.Column("check_key", sa.String(length=300), nullable=False),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
            comment="Why the rules could not choose, in plain words.",
        ),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The competing requirements and how they ranked, so the person sees what the rules saw.",
        ),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", "dismissed", name="conflict_status"),
            nullable=False,
        ),
        sa.Column("winner_requirement_id", sa.UUID(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'resolved' OR (resolved_by IS NOT NULL AND resolved_at IS NOT NULL)",
            name="ck_requirement_conflict_resolved_by_a_person",
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rule_set_id"], ["rule_set.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_requirement_conflict_status", "requirement_conflict", ["status"], unique=False
    )
    op.create_index(
        "uq_requirement_conflict_open",
        "requirement_conflict",
        ["rule_set_id", "check_key"],
        unique=True,
        postgresql_where="status = 'open'",
    )
    op.add_column(
        "requirement",
        sa.Column(
            "check_key",
            sa.String(length=300),
            nullable=True,
            comment="What this requirement checks, normalized. Two requirements sharing a check_key are competing to govern the same check and go through precedence resolution together. Computed at compile time; a curator can edit it to group requirements the rule missed. See docs/OPEN_QUESTIONS.md Q17.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requirement", "check_key")
    op.drop_index(
        "uq_requirement_conflict_open",
        table_name="requirement_conflict",
        postgresql_where="status = 'open'",
    )
    op.drop_index("ix_requirement_conflict_status", table_name="requirement_conflict")
    op.drop_table("requirement_conflict")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS conflict_status")
