"""access constraints

What a tech needs before they can check something. The capture plan defers an
item whose constraints the declared state of the walk does not satisfy.

Revision ID: 3c865082138b
Revises: 48f61c45ef60
Create Date: 2026-09-17 20:48:02.987304
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3c865082138b"
down_revision: str | None = "48f61c45ef60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # add_column does not create the enum type, even for an array of it.
    # See alembic/README.md.
    access_constraint = postgresql.ENUM(
        "requires_deenergized",
        "requires_ladder",
        "requires_confined_space_entry",
        name="access_constraint",
        create_type=False,
    )
    access_constraint.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requirement",
        sa.Column(
            "access_constraints",
            postgresql.ARRAY(
                sa.Enum(
                    "requires_deenergized",
                    "requires_ladder",
                    "requires_confined_space_entry",
                    name="access_constraint",
                )
            ),
            server_default="{}",
            nullable=False,
            comment="What the tech needs before they can check this. The capture plan defers an item whose constraints the tech's declared state does not satisfy, with the reason recorded.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requirement", "access_constraints")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS access_constraint")
