"""sync events

The field app's event log as received by the server. Every event is stored
before it is applied, and stored whether or not it can be applied: a rejected
event is a row saying why, not a dropped packet.

Revision ID: c6a834ef193a
Revises: 3c865082138b
Create Date: 2026-09-18 00:18:46.964445
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c6a834ef193a"
down_revision: str | None = "3c865082138b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_event",
        sa.Column("client_event_id", sa.UUID(), nullable=False),
        sa.Column("client_walk_id", sa.UUID(), nullable=False),
        sa.Column(
            "sequence",
            sa.Integer(),
            nullable=False,
            comment="Monotonic per walk on the device. Replay order, because device clocks drift.",
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "item_opened",
                "capture_taken",
                "gate_failed",
                "item_captured",
                "item_deferred",
                "walk_completed",
                name="sync_event_type",
            ),
            nullable=False,
        ),
        sa.Column("checklist_item_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Device clock. Not trusted for ordering.",
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "applied", "superseded", "rejected", name="sync_event_status"),
            nullable=False,
        ),
        sa.Column("outcome_note", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["submitted_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_event_id", name="uq_sync_event_client_event_id"),
    )
    op.create_index(
        "ix_sync_event_pending",
        "sync_event",
        ["status"],
        unique=False,
        postgresql_where="status = 'pending'",
    )
    op.create_index(
        "ix_sync_event_walk_sequence", "sync_event", ["client_walk_id", "sequence"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_event_walk_sequence", table_name="sync_event")
    op.drop_index(
        "ix_sync_event_pending", table_name="sync_event", postgresql_where="status = 'pending'"
    )
    op.drop_table("sync_event")
    # ### end Alembic commands ###
    for enum_name in ("sync_event_type", "sync_event_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
